title: Joshua Miller's Resume
email: resume@joshuadmiller.info
site-description: The online resume of Joshua Miller
in-development: false

sass:
    style: compressed

plugins:
    - jekyll-remote-theme
    
remote_theme: JoshuaTheMiller/Simple-Resume